import type { Metadata } from "next"
import { Noto_Serif } from "next/font/google"
import "./globals.css"
import { cn } from "@/lib/utils"
import { ThemeProvider } from "@/components/providers/themeProvider"
import { QueryProvider } from "@/components/providers/queryProvider"
import { ModalProvider } from "@/components/providers/modal-provider"
import { SocketProvider } from "@/components/providers/socket-provider"
import { ClerkProvider } from "@clerk/nextjs"
import { dark } from "@clerk/themes"

const notoSerif = Noto_Serif({
  subsets: ["latin"],
  variable: "--font-noto-serif",
  weight: ["300", "700"],
})

export const metadata: Metadata = {
  title: "Art Gallery Next",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon-16x16.png",
    apple: "/apple-touch-icon.png",
  },
}
export const viewport = {
  width: 1,
  themeColor: "dark",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider
      dynamic
      appearance={{ baseTheme: dark }}
      signInUrl='/sign-in'
      signUpUrl='/sign-up'
      signInFallbackRedirectUrl='/setup'
      signUpFallbackRedirectUrl='/'
      afterSignOutUrl='/'>
      <html lang='en' suppressHydrationWarning>
        <body className={cn(notoSerif.className, "antialiased")}>
          <ThemeProvider
            attribute={"class"}
            defaultTheme={"dark"}
            enableSystem
            storageKey='aganx-theme'>
            {/* <SocketProvider> */}
            <ModalProvider />
            <QueryProvider>{children}</QueryProvider>
            {/* </SocketProvider> */}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
