import type { Metadata } from "next"
import { Noto_Serif } from "next/font/google"
import "./globals.css"
import { cn } from "@/lib/utils"
import { ThemeProvider } from "@/components/providers/themeProvider"

const notoSerif = Noto_Serif({
  subsets: ["latin"],
  variable: "--font-noto-serif",
  weight: ["300", "700"],
})

export const metadata: Metadata = {
  title: "Art Gallery Next",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressContentEditableWarning>
      <body className={cn(notoSerif.className, "antialiased")}>
        <ThemeProvider
          attribute={"class"}
          defaultTheme={"dark"}
          enableSystem
          storageKey='aganex-theme'>
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
