import type { Metadata } from "next"
import { Noto_Serif } from "next/font/google"
import "./globals.css"

import { ModalProvider } from "@/components/providers/modal-provider"
import { QueryProvider } from "@/components/providers/queryProvider"
import { ThemeProvider } from "@/components/providers/themeProvider"
import { cn } from "@/lib/utils"
import { ClerkProvider } from "@clerk/nextjs"
import { TRPCReactProvider } from "@/trpc/client"

import { dark } from "@clerk/themes"

const notoSerif = Noto_Serif({
	subsets: ["latin"],
	variable: "--font-noto-serif",
	weight: ["300", "700"],
})

export const metadata: Metadata = {
	title: "Art Gallery Next",
	description: "Generated by create next app",
	icons: {
		apple: "/apple-touch-icon.png",
		icon: "/aganx.logo.png",
	},
}
export const viewport = {
	width: 1,
	themeColor: "dark",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<ClerkProvider
			dynamic
			appearance={{ baseTheme: dark }}
			afterSignOutUrl="/"
		>
			<TRPCReactProvider>
				<html lang="en" suppressHydrationWarning>
					<body className={cn(notoSerif.className, "antialiased")}>
						<ThemeProvider
							attribute={"class"}
							defaultTheme={"dark"}
							enableSystem
							storageKey="aganx-theme">
							<ModalProvider />
							<QueryProvider>{children}</QueryProvider>
						</ThemeProvider>
					</body>
				</html>
			</TRPCReactProvider>
		</ClerkProvider>
	)
}
